### ISSUE TITLE
`openSettings()` fails in menu-based MenuBarExtra

### ISSUE THREAD

**Issue by castdrian** [orchetect/SettingsAccess#2]
### Bug Description, Steps to Reproduce, Crash Logs, Screenshots, etc.

SettingsAccess/Utilities.swift:17: Fatal error: This method has no effect on macOS 14 or later.

**Comment by orchetect** [comment]
Are you compiling with Xcode 14? That's the only way that error should be happening.

**Comment by orchetect** [comment]
I've pushed release 1.1.0 which will now only compile on Xcode 15. That was originally intended and was a bit of an oversight to have allowed compiling on Xcode 14 which is where the error came from.

**Comment by castdrian** [comment]
this does not resolve the issue, it had been compiled with xcode 15 already, updating to the next minor still throws this exception

**Comment by orchetect** [comment]
I need more details about where you're using `.openSettingsAccess()` and where you're calling `openSettings()`.

**Comment by castdrian** [comment]
it's being chained onto mainmenuview in app.swift here
```swift
@main
struct ishare: App {
    @Default(.menuBarIcon) var menubarIcon
    @Default(.showMainMenu) var showMainMenu
    @StateObject private var appState = AppState()
    @NSApplicationDelegateAdaptor private var appDelegate : AppDelegate
    
    var body: some Scene {
        MenuBarExtra() {
            MainMenuView().openSettingsAccess()
        }
    label: {
        switch menubarIcon {
            case .DEFAULT: Image(nsImage: GlyphIcon)
            case .APPICON: Image(nsImage: AppIcon)
            case .SYSTEM: Image(systemName: "photo.on.rectangle.angled")
        }
    }
    .menuBarExtraAccess(isPresented: $showMainMenu)
        Settings {
            SettingsMenuView()
        }
    }
}
```
within MainMenuview the env is declared:

```swift
struct MainMenuView: View {    
    @StateObject private var availableContentProvider = AvailableContentProvider()
    @Environment(\.openSettings) private var openSettings
    
    var body: some View {
    ...

```

and then the method is called within a button
```swift
Button {
                NSApplication.shared.activate(ignoringOtherApps: true)
                openSettings()
} label: {
                Image(systemName: "gearshape")
                Label("Settings", image: String())
}.keyboardShortcut("s")
```

**Comment by orchetect** [comment]
Actually I think I've found solution. I'll try to push it today or tomorrow, just want to polish it up.

**Comment by orchetect** [comment]
Ok try release 1.2.0. The Demo project and readme are updated, but this is the gist:

- Remove `.openSettingsAccess()` from your `MenuBarExtra` menu view
- Inside `MainMenuView`, instead of your `Button`, use this:
  ```swift
  SettingsLink {
      Image(systemName: "gearshape")
      Text("Settings")
  } preAction: {
      NSApp.activate(ignoringOtherApps: true)
  } postAction: {
      // empty
  }
  .keyboardShortcut("s")
  ```

**Comment by castdrian** [comment]
lovely, whatever you did works much better than the actual SettingsLink component <3
